
version: "2.0"
services:
  web:
    image: php:7.0-apache
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./dockerconfig/virtualhosts.conf:/etc/apache2/sites-enabled/virtualhosts.conf
    
    links:
      - mysql

  mysql: 
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWOD: 123456
      MYSQL_DATABASE: mydb